name: Ultra-Low Size Av1an Encode
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct Link to Source Video'
        required: true
      output_name:
        description: 'Output Filename (No .mkv)'
        default: 'encoded_video'
        required: true
      start_time:
        description: 'Start Time (HH:MM:SS)'
        default: '00:00:00'
        required: false
      duration:
        description: 'Duration (HH:MM:SS) - 0 for full'
        default: '0'
        required: false

jobs:
  av1an-encode:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Disk Space
        run: sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost"

      - name: Download Source
        run: curl -g -L "${{ github.event.inputs.video_url }}" -o source_file.mkv

      - name: Run Av1an
        run: |
          # Setup FFmpeg seeking/duration
          FFMPEG_INPUT_ARGS="-ss ${{ github.event.inputs.start_time }}"
          if [ "${{ github.event.inputs.duration }}" != "0" ]; then
            FFMPEG_INPUT_ARGS="$FFMPEG_INPUT_ARGS -t ${{ github.event.inputs.duration }}"
          fi

          # Using Docker for Av1an
          # Changed --split-method to the newer syntax and used ffmpeg for scene detection
          docker run --rm -v $(pwd):/files masterofzen/av1an:latest \
            -i /files/source_file.mkv \
            -f "$FFMPEG_INPUT_ARGS" \
            --verbose \
            --encoder svt-av1 \
            --video-params " --preset 6 --crf 55 --tune 0 --enable-tpl-la 1 --aq-mode 1 --enable-overlays 1 " \
            --audio-params "-c:a libopus -b:a 32k" \
            --sc-method ffmpeg \
            -o "/files/${{ github.event.inputs.output_name }}.mkv"

      - name: Cleanup Source
        run: rm source_file.mkv

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: "Av1an-Output"
          path: "./*.mkv"
          if-no-files-found: error
